### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by RobLoach** [blend2d/b2d#1]
Is Blend2D a thing? Where is the source located? Was looking to try it out.

**Comment by hyOzd** [comment]
There is some information on the [homepage](https://blend2d.com/) under "Alpha and Beta Releases" title. It seems source code is shared with select people/organizations upon request.

**Comment by martin31821** [comment]
That's correct. Blend2D is currently in closed alpha and the source code is shared with selected people. You can check out the gitter linked on the website for more information and discussions.

**Comment by RobLoach** [comment]
Thanks! Joined the Gitter, and am excited to see what machines I can compile it for. Keep it up :+1:
